// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://fvzgahcffrcltpedvgdf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ2emdhaGNmZnJjbHRwZWR2Z2RmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njc4MzYzMDIsImV4cCI6MjA4MzQxMjMwMn0.NZCLrdUg1I-bN-rQ2g0uwE2KKUTRSZKuDGd49jHBqRw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);