// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://toeveqifqzdevwxzjgao.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRvZXZlcWlmcXpkZXZ3eHpqZ2FvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg5MDQxNTEsImV4cCI6MjA4NDQ4MDE1MX0.2lTms5GXsptpIW6g6AWEJORxrVkXGb1Lx5asFuV5vZs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);